# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-11 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name=b'Name')),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
