# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-12 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220712_0914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerAdd',
        ),
    ]
